name: check

on:
  pull_request:
    paths-ignore:
    - '**.md'
  push:
    paths-ignore:
    - '**.md'

jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        emacs_version:
          - 27.2
          - 28.2
          - 29.3
          - 30.2
    steps:

    - name: Set up Emacs
      uses: jcs090218/setup-emacs@master
      with:
        version: ${{matrix.emacs_version}}

    - name: Install Eldev
      uses: emacs-eldev/setup-eldev@v1

    - name: Check out the source code
      uses: actions/checkout@v4

    - name: Test the project
      run: |
        eldev -p -dtT doctor
        # eldev -p -dtT lint # complains about too-long lines, ignoring .dir-locals.el
        eldev -p -dtT test
